// 互通验收用的最小服务定义。字段特意覆盖几类容易出岔子的类型：
// int64（proto3 JSON 里是字符串）、枚举（是名字不是数字）、repeated、嵌套。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.1
// source: greet.proto

package greetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mood int32

const (
	Mood_MOOD_UNKNOWN Mood = 0
	Mood_MOOD_HAPPY   Mood = 1
	Mood_MOOD_TIRED   Mood = 2
)

// Enum value maps for Mood.
var (
	Mood_name = map[int32]string{
		0: "MOOD_UNKNOWN",
		1: "MOOD_HAPPY",
		2: "MOOD_TIRED",
	}
	Mood_value = map[string]int32{
		"MOOD_UNKNOWN": 0,
		"MOOD_HAPPY":   1,
		"MOOD_TIRED":   2,
	}
)

func (x Mood) Enum() *Mood {
	p := new(Mood)
	*p = x
	return p
}

func (x Mood) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mood) Descriptor() protoreflect.EnumDescriptor {
	return file_greet_proto_enumTypes[0].Descriptor()
}

func (Mood) Type() protoreflect.EnumType {
	return &file_greet_proto_enumTypes[0]
}

func (x Mood) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mood.Descriptor instead.
func (Mood) EnumDescriptor() ([]byte, []int) {
	return file_greet_proto_rawDescGZIP(), []int{0}
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Times         int64                  `protobuf:"varint,2,opt,name=times,proto3" json:"times,omitempty"`
	Mood          Mood                   `protobuf:"varint,3,opt,name=mood,proto3,enum=greet.Mood" json:"mood,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_greet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_greet_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest) GetTimes() int64 {
	if x != nil {
		return x.Times
	}
	return 0
}

func (x *HelloRequest) GetMood() Mood {
	if x != nil {
		return x.Mood
	}
	return Mood_MOOD_UNKNOWN
}

func (x *HelloRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ServedAt      int64                  `protobuf:"varint,2,opt,name=served_at,json=servedAt,proto3" json:"served_at,omitempty"`
	Detail        *Detail                `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_greet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_greet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_greet_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelloReply) GetServedAt() int64 {
	if x != nil {
		return x.ServedAt
	}
	return 0
}

func (x *HelloReply) GetDetail() *Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type Detail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Cached        bool                   `protobuf:"varint,2,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail) Reset() {
	*x = Detail{}
	mi := &file_greet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail) ProtoMessage() {}

func (x *Detail) ProtoReflect() protoreflect.Message {
	mi := &file_greet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail.ProtoReflect.Descriptor instead.
func (*Detail) Descriptor() ([]byte, []int) {
	return file_greet_proto_rawDescGZIP(), []int{2}
}

func (x *Detail) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *Detail) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

var File_greet_proto protoreflect.FileDescriptor

const file_greet_proto_rawDesc = "" +
	"\n" +
	"\vgreet.proto\x12\x05greet\"m\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05times\x18\x02 \x01(\x03R\x05times\x12\x1f\n" +
	"\x04mood\x18\x03 \x01(\x0e2\v.greet.MoodR\x04mood\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"j\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1b\n" +
	"\tserved_at\x18\x02 \x01(\x03R\bservedAt\x12%\n" +
	"\x06detail\x18\x03 \x01(\v2\r.greet.DetailR\x06detail\"8\n" +
	"\x06Detail\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x16\n" +
	"\x06cached\x18\x02 \x01(\bR\x06cached*8\n" +
	"\x04Mood\x12\x10\n" +
	"\fMOOD_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"MOOD_HAPPY\x10\x01\x12\x0e\n" +
	"\n" +
	"MOOD_TIRED\x10\x022t\n" +
	"\aGreeter\x122\n" +
	"\bSayHello\x12\x13.greet.HelloRequest\x1a\x11.greet.HelloReply\x125\n" +
	"\aChatter\x12\x13.greet.HelloRequest\x1a\x11.greet.HelloReply(\x010\x01b\x06proto3"

var (
	file_greet_proto_rawDescOnce sync.Once
	file_greet_proto_rawDescData []byte
)

func file_greet_proto_rawDescGZIP() []byte {
	file_greet_proto_rawDescOnce.Do(func() {
		file_greet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_greet_proto_rawDesc), len(file_greet_proto_rawDesc)))
	})
	return file_greet_proto_rawDescData
}

var file_greet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_greet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_greet_proto_goTypes = []any{
	(Mood)(0),            // 0: greet.Mood
	(*HelloRequest)(nil), // 1: greet.HelloRequest
	(*HelloReply)(nil),   // 2: greet.HelloReply
	(*Detail)(nil),       // 3: greet.Detail
}
var file_greet_proto_depIdxs = []int32{
	0, // 0: greet.HelloRequest.mood:type_name -> greet.Mood
	3, // 1: greet.HelloReply.detail:type_name -> greet.Detail
	1, // 2: greet.Greeter.SayHello:input_type -> greet.HelloRequest
	1, // 3: greet.Greeter.Chatter:input_type -> greet.HelloRequest
	2, // 4: greet.Greeter.SayHello:output_type -> greet.HelloReply
	2, // 5: greet.Greeter.Chatter:output_type -> greet.HelloReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_greet_proto_init() }
func file_greet_proto_init() {
	if File_greet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_greet_proto_rawDesc), len(file_greet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greet_proto_goTypes,
		DependencyIndexes: file_greet_proto_depIdxs,
		EnumInfos:         file_greet_proto_enumTypes,
		MessageInfos:      file_greet_proto_msgTypes,
	}.Build()
	File_greet_proto = out.File
	file_greet_proto_goTypes = nil
	file_greet_proto_depIdxs = nil
}
